import './globals.css'
import Navbar from './nav'
import Footer from './footer'


export const metadata = {
  title: 'Ejemplo de Next App Router',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Navbar></Navbar>
        <main className="borde relleno bg-lavanda">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
